### ISSUE TITLE
local install error, pls help

### ISSUE THREAD

**Issue by matureshadow** [piddnad/DDColor#38]
At first I use `python=3.8` which as told from [https://github.com/piddnad/DDColor](), but got error like below
```
ERROR: Ignored the following yanked versions: 0.20.0.dev0, 0.20.0rc2, 0.20.0rc3, 0.20.0rc6, 0.20.0rc7
ERROR: Ignored the following versions that require a different python version: 0.22.0 Requires-Python >=3.9; 0.22.0rc1 Requires-Python >=3.9; 0.23.0 Requires-Python >=3.10; 0.23.0rc0 Requires-Python >=3.10; 0.23.0rc2 Requires-Python >=3.10; 0.23.1 Requires-Python >=3.10; 0.23.2 Requires-Python >=3.10; 0.23.2rc1 Requires-Python >=3.10; 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.11.4 Requires-Python >=3.9; 1.12.0 Requires-Python >=3.9; 1.12.0rc1 Requires-Python >=3.9; 1.12.0rc2 Requires-Python >=3.9; 1.13.0 Requires-Python >=3.9; 1.13.0rc1 Requires-Python >=3.9; 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 1.26.0rc1 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9; 1.26.2 Requires-Python >=3.9; 1.26.3 Requires-Python >=3.9; 1.26.4 Requires-Python >=3.9; 2.0.0b1 Requires-Python >=3.9; 2.0.0rc1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement scikit-image==0.22.0 (from versions: 0.7.2, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.3, 0.10.0, 0.10.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.5, 0.15.0, 0.16.2, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.19.0rc0, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.20.0rc4, 0.20.0rc5, 0.20.0rc8, 0.20.0, 0.21.0rc0, 0.21.0rc1, 0.21.0)
ERROR: No matching distribution found for scikit-image==0.22.0
``` 
I realized maybe the python version is low, so i changed into 'python3.10' beacuase the erros msg said `Requires-Python >=3.10` but still error like below
```
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running bdist_wheel
      running build
      running build_ext
      <string>:125: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      Building extension for Python 3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)]
      Invoking CMake setup: 'cmake C:\Users\shadow\AppData\Local\Temp\pip-install-373trf7q\dlib_669ba91aa7214a9eb95805ba13046fd7\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\shadow\AppData\Local\Temp\pip-install-373trf7q\dlib_669ba91aa7214a9eb95805ba13046fd7\build\lib.win-amd64-cpython-310 -DPYTHON_EXECUTABLE=D:\soft\miniconda3\envs\python310\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\shadow\AppData\Local\Temp\pip-install-373trf7q\dlib_669ba91aa7214a9eb95805ba13046fd7\build\lib.win-amd64-cpython-310 -A x64'
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:5 (message):



        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


        You must use Visual Studio to build a python extension on windows.  If you
        are getting this error it means you have not installed Visual C++.  Note
        that there are many flavors of Visual Studio, like Visual Studio for C#
        development.  You need to install Visual Studio for C++.


        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!




      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "D:\soft\miniconda3\envs\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\soft\miniconda3\envs\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\soft\miniconda3\envs\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 218, in <module>
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\shadow\AppData\Local\Temp\pip-build-env-b5s6o_5j\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 130, in run
        File "<string>", line 167, in build_extension
        File "D:\soft\miniconda3\envs\python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\shadow\\AppData\\Local\\Temp\\pip-install-373trf7q\\dlib_669ba91aa7214a9eb95805ba13046fd7\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\shadow\\AppData\\Local\\Temp\\pip-install-373trf7q\\dlib_669ba91aa7214a9eb95805ba13046fd7\\build\\lib.win-amd64-cpython-310', '-DPYTHON_EXECUTABLE=D:\\soft\\miniconda3\\envs\\python310\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\shadow\\AppData\\Local\\Temp\\pip-install-373trf7q\\dlib_669ba91aa7214a9eb95805ba13046fd7\\build\\lib.win-amd64-cpython-310', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects
```

So, i don't know how to fix it, somewhere wrong? Any help will be appreciated.

**Comment by piddnad** [comment]
Hi @matureshadow, according to the error message, it may be a problem with installing dlib on windows. 
Perhaps you can refer to this: https://stackoverflow.com/a/76630254

**Comment by git9875** [comment]
I solved this issue in my Windows WSL (Ubuntu) installation.
Updated requirements.txt:   dlib==19.24.9

pip install cmake==4.0.0
pip install dlib==19.24.9
pip install -r requirements.txt
