### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by MOr1s2** [piddnad/DDColor#46]
Hello, thanks for your excellent work.
I encountered some problems during training,  the code error is as follows: 

[2024-07-24 11:56:18,281] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 0 (pid: 14366) of binary: 
...
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
basicsr/train.py FAILED

How can I fix it？

**Comment by piddnad** [comment]
Hi @MOr1s2 , it is difficult to determine what the problem is from this error log. Can you provide a more detailed error log?

**Comment by MOr1s2** [comment]
I used the recommended environment and used 4 A10s for training.
The detailed error information is as follows：

[2024-07-24 00:34:09,431] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 6208 closing signal SIGTERM
[2024-07-24 00:34:09,431] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 6211 closing signal SIGTERM
/home/envs/ddcolor/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 32 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/home/envs/ddcolor/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 32 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[2024-07-24 00:34:13,660] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 1 (pid: 6209) of binary: /home/envs/ddcolor/bin/python3
Traceback (most recent call last):
  File "/home/envs/ddcolor/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/envs/ddcolor/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/envs/ddcolor/lib/python3.9/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/home/envs/ddcolor/lib/python3.9/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/home/envs/ddcolor/lib/python3.9/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/home/envs/ddcolor/lib/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/envs/ddcolor/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/envs/ddcolor/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
basicsr/train.py FAILED
------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-24_00:34:09
  host      : VM-192-150-centos
  rank      : 2 (local_rank: 2)
  exitcode  : -11 (pid: 6210)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 6210
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-24_00:34:09
  host      : VM-192-150-centos
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 6209)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 6209
======================================================
/home/envs/ddcolor/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 32 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/home/envs/ddcolor/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 32 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by piddnad** [comment]
This is weird. I haven't encountered similar problems. If the environment is set correctly, I think it is necessary to check whether the CPU memory and GPU memory are overflowing.
Also found a similar issue (https://github.com/pytorch/pytorch/issues/76894), which was resolved after switching to tmux.

**Comment by MOr1s2** [comment]
However, the CPU memory and GPU memory is sufficient. I recreated an environment with python 3.9 and pytorch 1.13.0, and problem solved. Thanks for your help anyway :)
